//
// AirshipType.h
//
// Loire
// Created by Cuero Zhun Qu on 14-08-28.
// Generated by python script.
// Please don't edit this file.
//
//

#ifndef Loire_AirshipType_h
#define Loire_AirshipType_h

enum AirshipType {PLANE = 1, RUBBISH = 2, SHIP1 = 3, STUPID = 4, SHIP3 = 5, FORDISPLAY = 7, RUBBISH2 = 6};

#endif