//
// ProjectileType.h
//
// Loire
// Created by Cuero Zhun Qu on 14-08-20.
// Generated by python script.
// Please don't edit this file.
//
//

#ifndef Loire_ProjectileType_h
#define Loire_ProjectileType_h

enum ProjectileType {PROJECTILE1 = 1, LASER1 = 2, TORPEDO = 3, LASER2 = 4, LASER3 = 5, BOOM = 6};

#endif