//
// TechmodType.h
//
// Loire
// Created by Cuero Zhun Qu on 14-08-07.
// Generated by python script.
// Please don't edit this file.
//
//

#ifndef Loire_TechmodType_h
#define Loire_TechmodType_h

enum TechmodType {VACANTTECH = 0, RESPRING = 1};

#endif