//
// WeaponType.h
//
// Loire
// Created by Cuero Zhun Qu on 14-08-05.
// Generated by python script.
// Please don't edit this file.
//
//

#ifndef Loire_WeaponType_h
#define Loire_WeaponType_h

enum WeaponType {VACANT = 0, WEAPON1 = 1, WEAPON2 = 2, WEAPON3 = 3, TORPEDOWEAPON = 4};

#endif